version: "3.7"
services:
  catalog-service-1:
    build:
      context: ../catalog/
      dockerfile: Dockerfile
#    ports:
#      - "8081:8081"
    environment:
      - CATALOG_APP_HELLO_MSG=Hello-1
  catalog-service-2:
    build:
      context: ../catalog/
      dockerfile: Dockerfile
#    ports:
#      - "8081:8081"
    environment:
      - CATALOG_APP_HELLO_MSG=Hello-2
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
